package com.deedee.thelemia.audio.enumerate;

public enum AudioControl {
    PLAY_SOUND,
    PLAY_SOUND_WITH_TWEAK,
    STOP_SOUND,
    LOOP_SOUND,
    LOOP_SOUND_WITH_TWEAK,

    PLAY_MUSIC,
    PLAY_MUSIC_WITH_EFFECT,
    STOP_MUSIC,
    STOP_MUSIC_WITH_EFFECT,
    PAUSE_MUSIC,
    PAUSE_MUSIC_WITH_EFFECT,
    RESUME_MUSIC_SAME_CONFIG,
    RESUME_MUSIC,
    RESUME_MUSIC_SAME_CONFIG_WITH_EFFECT,
    RESUME_MUSIC_WITH_EFFECT,

    APPLY_PLAYING_EFFECT
}
